### PR TITLE
appdata: Add minimal release info

### PR DESCRIPTION
**Pull request by Lctrs**
This has to be updated on each new release. Don't know if this can somehow be automated with Meson.

### CODE REVIEW

**Comment by benzea** [comment]
Alright, if you are adding more commits …

In my view, the prefix in the commit message should describe where the change is happening. In this case it would be good for it to be `data:` (for the directory) or simply `appdata:` as that makes things really clear. So, it would be better to do e.g. `appdata: Add minimal release info`.

**Comment by Lctrs** [comment]
> Alright, if you are adding more commits …

?

**Comment by Lctrs** [comment]
@benzea Understood.

**Comment by benzea** [comment]
Thanks!

Yeah, "Enhancement:" just isn't great in my view. But I didn't want to complain about one commit for the other PR :)

**Comment by Lctrs** [comment]
Yeah, I agree.

On another subject, would you be interested if I open a PR for the flatpak recipe here with the changes made in Flathub once it has been merged ?

**Comment by benzea** [comment]
Sure, not sure how useful it is, but I guess one might build test versions of gnome-network-displays from CI in the long run that way.

**Pull request merged**
